.\" Manpage for ab-chroot.
.\" contact yujimaarif.ym@gmail.com to correct errors or typos.
.TH man 8 "09 Maret 2016" "1.0" "ab-chroot man page"
.SH NAME
ab-chroot \- goes to root asboot
.SH SYNOPSIS
chroot to asboot gnu/linux system
.SH DESCRIPTION
ab-chroot is tools using for chrooting asboot gnu/linux system
.SH OPTIONS
ab-chroot <mountpoint root system>
.SH BUGS
you must be kidding no bugs in this script if you find bugs please contact yujimaarif@gmail.com
.SH AUTHOR
Arba z.m (korep) <yujimaarif.ym@gmail.com>

